spring.application.name=auth-service

# PostgreSQL Database
spring.datasource.url=jdbc:postgresql://localhost:5432/rlearnhub
spring.datasource.username=rlearnhub
spring.datasource.password=rlearnhub123
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Auth Service Port
server.port=8085