spring.application.name=resource-service

# PostgreSQL Database
spring.datasource.url=jdbc:postgresql://localhost:5432/rlearnhub
spring.datasource.username=rlearnhub
spring.datasource.password=rlearnhub123
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Resource Service Port
server.port=8082

# File Upload Settings
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB