spring.application.name=api-gateway

server.port=8080


# =========================
# AUTH SERVICE
# =========================

spring.cloud.gateway.server.webflux.routes[0].id=auth-service
spring.cloud.gateway.server.webflux.routes[0].uri=http://localhost:8081
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/api/auth/**
spring.cloud.gateway.server.webflux.routes[0].filters[0]=DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin


# =========================
# RESOURCE SERVICE
# =========================

spring.cloud.gateway.server.webflux.routes[1].id=resource-service
spring.cloud.gateway.server.webflux.routes[1].uri=http://localhost:8082
spring.cloud.gateway.server.webflux.routes[1].predicates[0]=Path=/api/resources/**
spring.cloud.gateway.server.webflux.routes[1].filters[0]=DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin


spring.cloud.gateway.server.webflux.routes[2].id=subject-service
spring.cloud.gateway.server.webflux.routes[2].uri=http://localhost:8082
spring.cloud.gateway.server.webflux.routes[2].predicates[0]=Path=/api/subjects/**


spring.cloud.gateway.server.webflux.routes[3].id=download-service
spring.cloud.gateway.server.webflux.routes[3].uri=http://localhost:8082
spring.cloud.gateway.server.webflux.routes[3].predicates[0]=Path=/api/downloads/**


# =========================
# NOTIFICATION SERVICE
# =========================

spring.cloud.gateway.server.webflux.routes[4].id=notification-service
spring.cloud.gateway.server.webflux.routes[4].uri=http://localhost:8083
spring.cloud.gateway.server.webflux.routes[4].predicates[0]=Path=/api/notifications/**
spring.cloud.gateway.server.webflux.routes[4].filters[0]=DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin


spring.cloud.gateway.server.webflux.routes[5].id=announcement-service
spring.cloud.gateway.server.webflux.routes[5].uri=http://localhost:8083
spring.cloud.gateway.server.webflux.routes[5].predicates[0]=Path=/api/announcements/**
spring.cloud.gateway.server.webflux.routes[5].filters[0]=DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin


# =========================
# DASHBOARD SERVICE
# =========================

spring.cloud.gateway.server.webflux.routes[6].id=dashboard-service
spring.cloud.gateway.server.webflux.routes[6].uri=http://localhost:8084
spring.cloud.gateway.server.webflux.routes[6].predicates[0]=Path=/api/dashboard/**


# =========================
# CORS
# =========================

spring.cloud.gateway.server.webflux.globalcors.cors-configurations.[/**].allowedOrigins=http://localhost:5173
spring.cloud.gateway.server.webflux.globalcors.cors-configurations.[/**].allowedMethods=GET,POST,PUT,DELETE,OPTIONS
spring.cloud.gateway.server.webflux.globalcors.cors-configurations.[/**].allowedHeaders=*
spring.cloud.gateway.server.webflux.globalcors.add-to-simple-url-handler-mapping=true